project:
  type: book

book:
  title: "Quarto example"
  author: "Jane Doe"
  date: "05/08/2021"
  chapters:
    - index.qmd
    - intro.Rmd
    - summary.qmd
    - references.qmd

filters:
  - at: pre-ast
    type: json
    path: filter_pre.py
  - at: pre-ast
    type: json
    path: filter_divspans.py
  - at: pre-ast
    path: add-meta.lua
  - at: pre-ast
    type: json
    path: mark_notebooks.py
  - at: post-quarto
    type: json
    path: write_meta.py
  - at: post-quarto
    type: json
    path: write_doc.py
  - at: post-quarto
    type: json
    path: export_notebooks.py
  - at: post-quarto
    type: json
    path: filter_nb_only.py

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport

noteout:
  filter-divspans: ['r']
  nb-format: ipynb
  interact-url: https://example.com?filepath=python-book/
  book-url-root: https://example.com
  nb-dir: .

processing:
  language: python
  kernel-name: python
  kernel-display: "Python (Pyodide)"
  interact-data-root: null
