name: Unit tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.local
          key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('test-requirements.txt') }}

      - name: Install R
        run: |
          sudo apt install -y r-base

      - name: Install R packages
        run: |
          sudo Rscript -e 'install.packages(c("quarto", "reticulate"))'

      - name: Install pandoc
        run: |
          sudo apt install -y curl
          curl -LO https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-1-amd64.deb
          sudo dpkg --install pandoc-2.14.1-1-amd64.deb

      - name: Install quarto
        run: |
          curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v0.2.62/quarto-0.2.62-amd64.deb
          sudo dpkg --install quarto-0.2.62-amd64.deb

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install package
        run: |
          pip install flit
          flit install -s

      - name: Install test requirements
        run: pip install -r test-requirements.txt

      - name: Run tests
        run: pytest noteout
