name: Unit tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      QUARTO_VER: "1.6.1"
      PANDOC_VER: "3.2"

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.local
          key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('test-requirements.txt') }}

      - name: Install R
        run: |
          sudo apt install -y r-base

      - name: Install R packages
        run: |
          sudo Rscript -e 'install.packages(c("quarto", "reticulate"))'

      - name: Install quarto and matching pandoc
        run: |
          sudo apt install -y curl
          curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VER}/quarto-${QUARTO_VER}-linux-amd64.deb -o quarto.deb
          # PANDOC appends -1 to the archive root name for .deb packages.
          curl -L https://github.com/jgm/pandoc/releases/download/${PANDOC_VER}/pandoc-${PANDOC_VER}-1-amd64.deb -o pandoc.deb
          sudo dpkg --install quarto.deb pandoc.deb
          # Install Tex setup to build PDF.
          quarto install tinytex

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install package
        run: |
          pip install flit
          flit install -s

      - name: Install test requirements
        run: pip install -r test-requirements.txt

      - name: Run tests
        run: pytest tests
